version: 0.2
phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION ECR_REPO_URI=$ECR_REPO_URI CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
    - REPO_URI=$ECR_REPO_URI
    - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
    - ls -la
    - echo Building the Docker image...
    - docker build -t $REPO_URI:latest .
    - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
    - echo Pushing the Docker images...
    - docker push $REPO_URI:latest
    - docker push $REPO_URI:$IMAGE_TAG
    - printf '[{"name":"app","imageUri":"%s:%s"}]' $REPO_URI $IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json